#!/bin/bash

DAYS=10
TIME=$((${DAYS}*24*1*3600))

for domain in $(cat validate-ssl-domains.txt); do
  if ! true | openssl s_client -connect ${domain}:443 2>/dev/null | \
    openssl x509 -noout -checkend ${TIME} >/dev/null; then
      echo "Certificado próximo a vender, revisarlo ${domain}"
  fi
done
